apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nodejs-sample-1-staging

images:
- digest: sha256:309b50aa66f10d13707e67352d09ac7ade00361a3dfeaa1026965cbdc3396a88
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: image-registry.openshift-image-registry.svc:5000/nodejs-sample-1-develop/nodejs-sample-1-record
